# Standalone Reproduction Script Generated by InsightFlow
# Session ID: session_1782279768724
# Target Column: salary
# Task Type: regression
# Best Model Trained: LinearRegression
#
# Exclusions Applied:
#   - employee_id: ID-like: near-unique column (400 unique values out of 400 rows)
#   - name: ID-like: near-unique column (400 unique values out of 400 rows)

import sys
import os
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LinearRegression

def main():
    if len(sys.argv) < 2:
        print("Usage: python reproduce.py <path_to_raw_csv>")
        sys.exit(1)
        
    csv_path = sys.argv[1]
    if not os.path.exists(csv_path):
        print(f"Error: File '{csv_path}' does not exist.")
        sys.exit(1)
        
    print(f"Loading raw dataset from {csv_path}...")
    try:
        df = pd.read_csv(csv_path)
    except Exception as e:
        print(f"Error loading CSV file: {e}")
        sys.exit(1)
        
    # Replace empty strings and whitespace-only strings with NaN
    df = df.replace(r'^\s*$', np.nan, regex=True)
    
    # Try to convert each column to numeric if possible (matching parse_request_data)
    for col in df.columns:
        try:
            df[col] = pd.to_numeric(df[col])
        except (ValueError, TypeError):
            pass
            
    print(f"Loaded dataset: {df.shape[0]} rows, {df.shape[1]} columns.")
    
    # Apply exclusions
    excluded_cols = ['employee_id', 'name']
    print(f"Dropping excluded and leakage columns: {excluded_cols}")
    df = df.drop(columns=excluded_cols, errors='ignore')
    
    # Target validation
    target_col = "salary"
    if target_col not in df.columns:
        print(f"Error: Target column '{target_col}' not found in dataset columns: {list(df.columns)}")
        sys.exit(1)
        
    y = df[target_col]
    X = df.drop(columns=[target_col])
    
    # Drop rows where target is missing
    nan_mask = y.isna()
    if nan_mask.any():
        print(f"Dropping {nan_mask.sum()} rows with missing target values.")
        X = X[~nan_mask]
        y = y[~nan_mask]
    
    # Identify numeric and categorical columns
    numeric_cols = X.select_dtypes(include=[np.number]).columns.tolist()
    categorical_cols = X.select_dtypes(exclude=[np.number]).columns.tolist()
    
    # Build preprocessing pipeline matching LeakageSafePipeline in backend/src/modeling.py
    transformers = []
    if numeric_cols:
        transformers.append(
            ("num", Pipeline([
                ("imp", SimpleImputer(strategy="median")),
                ("sc", StandardScaler())
            ]), numeric_cols)
        )
    if categorical_cols:
        transformers.append(
            ("cat", Pipeline([
                ("imp", SimpleImputer(strategy="most_frequent")),
                ("oh", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
            ]), categorical_cols)
        )
    
    preprocessor = ColumnTransformer(transformers=transformers, remainder="drop")
    
    # Estimator setup
    # Gated to n_jobs=1 on Windows due to OpenMP/joblib duplicate runtime deadlock, -1 (max parallel) on Linux
    n_jobs_val = 1 if sys.platform == "win32" else -1
    estimator = LinearRegression(n_jobs=n_jobs_val)
    
    # Fit the pipeline
    pipeline = Pipeline([
        ("preprocessor", preprocessor),
        ("model", estimator)
    ])
    
    print("Fitting model...")
    pipeline.fit(X, y)
    print("Model fit complete!")
    
    # ── Visualizations ──
    print("Generating visualizations...")
    
    # Plot 1: Target Distribution
    plt.figure(figsize=(8, 5))
    plt.hist(y.dropna(), bins=20, color='#14b8c8', edgecolor='black')
    plt.ylabel("Frequency")
    plt.xlabel(target_col)
    plt.title(f"Target Distribution: {target_col}")
    plt.tight_layout()
    plot1_path = "target_distribution.png"
    plt.savefig(plot1_path)
    plt.close()
    print(f"  Saved target distribution plot to {plot1_path}")
    
    # Plot 2: Feature-vs-Target Plot
    corr_feature = None
    is_numeric_feature = False
    if numeric_cols:
        corr_feature = numeric_cols[0]
        is_numeric_feature = True
    elif categorical_cols:
        corr_feature = categorical_cols[0]
        is_numeric_feature = False
        
    if corr_feature:
        plt.figure(figsize=(8, 5))
        if is_numeric_feature:
            # Scatter plot for regression
            plt.scatter(X[corr_feature], y, alpha=0.6, color='#f59e0b')
            plt.ylabel(target_col)
            plt.xlabel(corr_feature)
        else:
            # Boxplot of regression target grouped by categorical feature
            data_to_plot = [y[X[corr_feature] == val].dropna() for val in X[corr_feature].dropna().unique()]
            labels = [str(val) for val in X[corr_feature].dropna().unique()]
            plt.boxplot(data_to_plot, labels=labels)
            plt.xlabel(corr_feature)
            plt.ylabel(target_col)
            
        plt.title(f"{corr_feature} vs {target_col}")
        plt.tight_layout()
        plot2_path = f"feature_vs_target_{corr_feature}.png"
        plt.savefig(plot2_path)
        plt.close()
        print(f"  Saved feature vs target plot to {plot2_path}")
        
    print("\nStandalone reproduction completed successfully!")

if __name__ == '__main__':
    main()
